---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    otrs:
      database:
        password: otrs
    mysql:
      server_debian_password: "foo"
      server_root_password: "foo"
      server_repl_password: "foo"

platforms:
  - name: debian-7.4
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[otrs::default]
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8085}]
      - ["private_network", {ip: "192.168.33.34"}]
