---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[otrs::default]
    attributes:
      otrs:
#        version: 2.4.15
#        version: 3.0.22
        version: 3.2.17
#        version: 3.3.15
        version: 4.0.14
#        version: 5.0.1
#        version: 5.0.3
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8086}]
      - ["forwarded_port", {guest: 443, host: 8087}]
      - ["private_network", {ip: "192.168.33.34"}]
