---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-8.5
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[otrs::default]
      - recipe[otrs_test::hostname]
    attributes:
      otrs:
        fqdn: otrs.vagrant
        database:
          password: otrs
      mysql:
        server_root_password: root
        server_repl_password: repl
    driver_config:
      network:
      - ["private_network", {ip: "192.168.33.34"}]
