---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    otrs:
      database:
        password: otrs
    mysql:
      server_debian_password: "foo"
      server_root_password: "foo"
      server_repl_password: "foo"

platforms:
  - name: debian-7.4
    run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[otrs::default]
    attributes:
      otrs:
#        version: 2.4.15
#        version: 3.3.15
        version: 4.0.14
#        version: 5.0.3
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8086}]
      - ["forwarded_port", {guest: 443, host: 8087}]
      - ["private_network", {ip: "192.168.33.34"}]
