name             "otrs"
maintainer       "TYPO3 Association"
maintainer_email "steffen.gebert@typo3.org"
license          "Apache 2.0"
description      "Installs/Configures OTRS"

version          "1.1.0"

depends          "apache2", "= 3.1.0"
depends          "build-essential", "= 2.0.6"
depends          "cron", "= 1.4.3"
depends          "database", "= 4.0.9"
depends          "mysql", "= 6.1.2"
depends          "mysql2_chef_gem", "= 1.0.2"
depends          "perl", "= 1.2.4"
